{{- if and .Values.networkPolicies.enabled (eq .Values.name "oc-frontend") }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: frontend-networkpolicy
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app:  oc-frontend
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          network.openshift.io/policy-group: ingress
  - from:
    - namespaceSelector:
        matchLabels:
          name: openshift-ingress
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: openshift-ingress
  - from: []
    ports:
    - protocol: TCP
      port: 8080
  egress:
  # Permitir tráfico HTTPS saliente a las rutas de OpenShift (para llamadas al backend-api)
  - to:
    - namespaceSelector:
        matchLabels:
          network.openshift.io/policy-group: ingress
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 80
  # Permitir tráfico al backend-api por nombre de servicio (dentro del cluster)
  - to:
    - podSelector:
        matchLabels:
          app: oc-backend-api
    ports:
    - protocol: TCP
      port: 3000
  # Permitir DNS
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: openshift-dns
    ports:
    - protocol: UDP
      port: 5353
    - protocol: TCP
      port: 5353
{{- end }}
{{- if and .Values.networkPolicies.enabled (eq .Values.name "oc-backend-api") }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: backend-api-networkpolicy
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: oc-backend-api
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: oc-frontend
    ports:
    - protocol: TCP
      port: 3000
  - from:
    - namespaceSelector:
        matchLabels:
          network.openshift.io/policy-group: ingress
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 80
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: backend-data
    ports:
    - protocol: TCP
      port: 3001
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: openshift-dns
    ports:
    - protocol: UDP
      port: 5353
    - protocol: TCP
      port: 5353
{{- end }}
{{- if and .Values.networkPolicies.enabled (eq .Values.name "oc-backend-data") }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: backend-data-networkpolicy
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: oc-backend-data
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: backend-api
    ports:
    - protocol: TCP
      port: 3001
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: database
    ports:
    - protocol: TCP
      port: 27017
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: openshift-dns
    ports:
    - protocol: UDP
      port: 5353
    - protocol: TCP
      port: 5353
{{- end }}
{{- if and .Values.networkPolicies.enabled (eq .Values.name "oc-database") }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: database-networkpolicy
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: oc-database
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: oc-backend-data
    ports:
    - protocol: TCP
      port: 27017
  egress:
  - to:
    - namespaceSelector: {}
      podSelector:
        matchLabels:
          app: openshift-dns
    ports:
    - protocol: UDP
      port: 53
{{- end }}